### ISSUE TITLE
zlibrary store installs but that's it

### ISSUE THREAD

**Issue by o20n3** [FabienZouaoui/calibre_zlibrary_store#1]
Can see Zlibrary as a plugin, can select it as a store, it does not display as an active store when searching, no parameters can be searched for as no store is active.

**Comment by FabienZouaoui** [comment]
Hi, the mirror I was using has been removed.
Updated now, thanks.

Please note that z-lib now use a javascript trick to block direct downloads so it is disabled at this moment.
I recommend to visit the store with calibre's internal browser. Files downloaded from here will be added to your library
